# 异常体系
- `RuntimeException` 
- `非RuntimeException` 编译时异常，在写的时候已经有红线提示了

![](https://obsidian-1307744200.cos.ap-guangzhou.myqcloud.com/%E5%9B%BE%E7%89%87/202403031014287.png)

>[!hint] JVM 会自己默认处理异常，那我们为什么还要自己处理呢？
>因为 JVM 的默认处理方案会终止程序的运行，但我们在实际开发中就算程序出错了，我们依然还要继续运行

>[!hint] 方法
>`getMessage()` 返回此异常的详细信息字符串
>`toString()`  返回简短的异常类名+异常原因
>`printStackTrace()`  输出异常错误信息到控制台【异常类名+位置+原因】

# 异常处理
## try…catch…
```java
try {
	可能出现异常的代码
	……
} catch(异常类名，变量名) {
	异常处理的代码
	……
}
……
A
```

***执行流程：***
1. 执行 try 内的代码
	1. 未出现异常，不执行 catch 内的代码
	2. 出现异常
		1. 生成一个异常类对象，该对象被提交给 Java 运行时系统
		2. Java 运行时系统到 catch 中匹配异常类，匹配成功，则执行 catch 内代码
		3. 接着继续向下执行，直到代码 A

## throws
>`throws` 仅仅是抛出异常，***并没有做任何处理***，所以程序遇到异常还是会终止

```java
public void method() throws 异常名 {
	……
}
```

>[!hint] 在我们处理不了时，或偷懒时，我们会选择 `throws`

# 自定义异常
```java
public class demo {
	// 异常类
	static class scoreException extends Exception {
		// 无参构造
		public scoreException() {}

		// 带参构造
		public scoreException(String message) {
			// 传给Exception，Exception传给Throwable中的detailMessage
			super(message);
		}
	}

	public static void main(String[] args) throws scoreException {
		Scanner sc = new Scanner(System.in);
		int i = sc.nextInt();
		
		if (i < 0 || i > 100){
			throw new scoreException（＂你输入的分数有误＂）；
		}else {
			System.out.println（＂分数正常＂）；
		}
	}
}
```



# 实例
## 注释异常
```java
System.out.println("bug");   //\u000A is a newline

---
java: 需要';'
```
>由于注释里的<mark style="background: #D2B3FFA6;">\u000A</mark>导致的，因为读程序时\u000A会转换为一个换行符

---

```java
System.out.println("bug");   //look inside c:\users

---
非法的Unicode转义
```
>由于\u后面没有跟着4位的十六进制数






























































